import {
  StudioProjectItem,
  StudioClientItem,
  StudioCertificateItem,
  StudioBlogItem,
} from "./types";

export const studioProjects: StudioProjectItem[] = [
  {
    slug: "retailos",
    title: "RetailOS",
    tagline: "Offline-first retail management platform.",
    description: "Complete retail inventory and billing system reducing stock discrepancies by 40% and cutting billing time to under 1 minute.",
    problem: "Small retail chains managing inventory with manual spreadsheets, leading to inventory discrepancies and slow billing.",
    results: "Deployed to 3 stores. 40% fewer stock discrepancies. 80% faster billing.",
    tech: ["Flutter", "Dart", "SQLite", "Hive"],
    accent: "#C9C7BE",
    index: "01",
  },
  {
    slug: "spendwise",
    title: "SpendWise",
    tagline: "Smart personal finance & visual budget analytics.",
    description: "Intuitive expense tracking app with smart categorization, budget thresholds, and actionable spending insights.",
    problem: "Existing trackers are either too bloated or lack actionable visual insights for real monthly habits.",
    results: "500+ downloads. 4.5-star rating. 30% higher savings awareness in 30 days.",
    tech: ["Flutter", "Firebase", "FL Chart", "Riverpod"],
    accent: "#8E9E8E",
    index: "02",
  },
  {
    slug: "playmate",
    title: "PlayMate",
    tagline: "Social sports player matching & court booking.",
    description: "Real-time sports matchmaking platform connecting local pickup players with nearby court availability.",
    problem: "Sports enthusiasts struggle to find compatible players and book courts without friction.",
    results: "200+ active players. 15+ weekly matches coordinated effortlessly.",
    tech: ["Flutter", "Node.js", "MongoDB", "Socket.io"],
    accent: "#B4B2A8",
    index: "03",
  },
  {
    slug: "student-companion",
    title: "Student Companion",
    tagline: "Unified academic productivity & deadline tracking.",
    description: "All-in-one companion with timetable scheduling, markdown note-taking, assignment alarms, and GPA projections.",
    problem: "Students juggle disconnected apps for schedules, grades, and reminders.",
    results: "Active across 5 universities. 95% deadline notification delivery rate.",
    tech: ["Flutter", "SQLite", "Local Notifications", "Provider"],
    accent: "#9DA0A8",
    index: "04",
  },
  {
    slug: "school-management-system",
    title: "School Management System",
    tagline: "Unified school operations & role-based administration.",
    description: "Full-scale administrative platform handling student attendance, grade records, parent broadcasts, and fee billing.",
    problem: "Disjointed record-keeping creating operational bottlenecks and poor parent satisfaction.",
    results: "Serving 500+ students across 2 campuses. 60% less administrative overhead.",
    tech: ["Flutter", "Firebase", "Cloud Functions", "Firestore"],
    accent: "#C9C7BE",
    index: "05",
  },
];

export const studioClients: StudioClientItem[] = [
  {
    slug: "retail-inventory-system",
    title: "Retail Inventory Management System",
    client: "Local Retail Chain",
    industry: "Retail & Commerce",
    challenge: "Manual paper and spreadsheet tracking causing 40%+ stock discrepancies and slow customer checkout queues.",
    outcome: "40% reduction in inventory errors. Checkout billing reduced from 5 min to under 1 min per customer.",
    description: "Architected a custom offline-first POS & inventory suite operating seamlessly across 3 retail store branches.",
    testimonial: {
      quote: "The system transformed how we manage our inventory. What used to take hours now takes minutes.",
      author: "Store Owner",
    },
  },
  {
    slug: "education-platform",
    title: "Education Management Platform",
    client: "Educational Institution",
    industry: "Education Technology",
    challenge: "Disjointed systems for attendance, student grading, and parent communications creating data silos.",
    outcome: "60% less administrative overhead. 80% improvement in parent satisfaction scores.",
    description: "Developed a comprehensive institutional portal serving 500+ students with tailored role-based portals.",
    testimonial: {
      quote: "Finally, a system that actually understands how schools work. The team delivered exactly what we needed.",
      author: "School Administrator",
    },
  },
];

export const studioCertificates: StudioCertificateItem[] = [
  {
    id: 1,
    image: "/certificates/1.png",
    title: "Flutter Advanced Development",
    description: "Architectural mastery in production state management, offline-first sync, and deep performance profiling.",
    issuer: "Udemy / Google Developer Experts",
    date: "2024",
    credentialId: "CERT-FLUTTER-94812",
  },
  {
    id: 2,
    image: "/certificates/2.png",
    title: "Google UX Design Professional",
    description: "End-to-end product design process from user research and wireframing to accessible high-fidelity prototypes.",
    issuer: "Google / Coursera",
    date: "2024",
    credentialId: "CERT-GDESIGN-38291",
  },
  {
    id: 3,
    image: "/certificates/3.png",
    title: "Cloud Computing & Serverless Architecture",
    description: "Designing scalable backend architectures, cloud functions, microservices, and database clustering.",
    issuer: "AWS / Google Cloud Certified",
    date: "2024",
    credentialId: "CERT-CLOUD-74910",
  },
  {
    id: 4,
    image: "/certificates/4.png",
    title: "Production Mobile Systems Engineering",
    description: "Engineering resilient native and cross-platform mobile architectures with rigorous automated testing.",
    issuer: "Mobile Engineering Guild",
    date: "2023",
    credentialId: "CERT-MOBENG-55102",
  },
  {
    id: 5,
    image: "/certificates/5.png",
    title: "Full-Stack Product Architecture",
    description: "Full-stack software design patterns, schema modeling, API contract testing, and deployment pipelines.",
    issuer: "Software Architecture Institute",
    date: "2023",
    credentialId: "CERT-ARCH-19348",
  },
  {
    id: 6,
    image: "/certificates/6.png",
    title: "Open Source Contributor Distinction",
    description: "Public contributions to open-source tooling, Flutter ecosystem packages, and community developer utilities.",
    issuer: "GitHub Developer Program",
    date: "2023",
    credentialId: "CERT-OSDEV-88201",
  },
];

export const studioBlog: StudioBlogItem[] = [
  {
    slug: "how-i-built-expense-tracker-flutter",
    title: "How I Built an Expense Tracker App in Flutter",
    description: "Architecture breakdown of SpendWise — state management with Riverpod and local SQLite encryption.",
    category: "Flutter",
    readingTime: "8 min read",
    date: "2025-12-15",
  },
  {
    slug: "flutter-architecture-large-applications",
    title: "Flutter Architecture for Large Applications",
    description: "Modular layering patterns for Flutter codebases scaling past prototypes into production.",
    category: "Architecture",
    readingTime: "12 min read",
    date: "2025-11-20",
  },
  {
    slug: "building-business-software-people-use",
    title: "Building Business Software That People Actually Use",
    description: "Field insights from engineering inventory and billing systems for daily operational retail staff.",
    category: "Product Design",
    readingTime: "10 min read",
    date: "2025-10-10",
  },
];
